Add new character type
glotzerlab/gsd pull request #391
Opened 2024-09-16 16:39 UTC by josephburkhart

## Description

These changes make the Python API more approachable by adding support for reading and writing strings to GSD data chunks. My changes add a new character data type on the C side, and modify the python api to automatically decode strings for the user. The new changes are accompanied by a new test, which fully covers the expected use cases.

## Motivation and Context

Currently, strings are implicitly encoded as uint8 data, but it is up to the user to figure out how to decode that data upon reading. The Python API is intended to be approachable, allowing users to, for example, create a pandas dataframe from a GSD log in [one line](https://gsd.readthedocs.io/en/v3.3.0/python-module-gsd.hoomd.html#gsd.hoomd.read_log). However, this oneliner will break if the log contains varying textual information, because pandas requires uniform dimensions in each column. These changes make it so users don't have to convert decimal unicode to text on their own, allowing the one-line example to work.

This PR resolves #375.

## How Has This Been Tested?

I have modified `test_fl.py`, adding a new test specifically for the string dtype (`test_string_dtype`). The new test covers both `fl` and `pygsd`.

- [ ] Please build the sphinx documentation and check that any changes to documentation display properly **(TODO)**

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/gsd/blob/trunk-patch/CONTRIBUTING.rst).
- [ ] I agree with the terms of the [**GSD Contributor Agreement**](https://github.com/glotzerlab/gsd/blob/trunk-patch/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`doc/credits.rst`) in the pull request source branch.
- [ ] I have added a change log entry to ``CHANGELOG.rst``.

2024-09-16 17:25 UTC, josephburkhart commented
pre-commit.ci autofix

2024-09-23 15:10 UTC, joaander requested changes
We need to remove stray `print()` calls, commented code, and unused imports.

2024-09-23 15:10 UTC, joaander commented on gsd/fl.pyx
> +cimport cython
```suggestion
```
Unused.

2024-09-23 15:10 UTC, joaander commented on gsd/fl.pyx
> +
```suggestion
```
Unused.

2024-09-23 15:10 UTC, joaander commented on gsd/fl.pyx
> +            #     data_ptr = __get_ptr_char(data_array)
```suggestion
```

2024-09-23 15:10 UTC, joaander commented on gsd/fl.pyx
> +                print(bytes_array[0].decode("UTF-8"))
```suggestion
```

2024-09-23 15:10 UTC, joaander commented on gsd/gsd.c
> +        {
```suggestion
    if ((handle->open_flags == GSD_OPEN_READWRITE || handle->open_flags == GSD_OPEN_APPEND)
        && (handle->header.gsd_version
            != gsd_make_version(GSD_CURRENT_FILE_VERSION_MAJOR, GSD_CURRENT_FILE_VERSION_MINOR))
        && (handle->header.gsd_version >> (sizeof(uint32_t) * 4) == GSD_CURRENT_FILE_VERSION_MAJOR)
        && (handle->header.gsd_version & 0xFFFF < GSD_CURRENT_FILE_VERSION_MINOR))
        {
```
There is no need to rewrite the header when it is already 2.1.

2024-09-23 15:10 UTC, joaander commented on gsd/gsd.c
> +        // label the file as a v2.1 file
```suggestion
        // GSD always writes files matching the current major and minor version.
```

2024-09-24 17:12 UTC, josephburkhart commented
Great catches - apologies for the omissions!

2024-09-25 14:14 UTC, joaander commented on gsd/gsd.c
> +        {
I reverted this redundant suggestion. During the review I failed to notice that we already checked `(handle->header.gsd_version != gsd_make_version(GSD_CURRENT_FILE_VERSION_MAJOR, GSD_CURRENT_FILE_VERSION_MINOR)`.

2024-09-25 14:14 UTC, joaander approved these changes
Thanks!

2024-10-18 14:30 UTC, joaander commented
I tested the original motivation for this feature.

In the `test_hoomd.py::read_log` test, pandas is indeed able to create a `DataFrame` with the strings:
```python
    import pandas
    df = pandas.DataFrame(logged_data_dict)
    print()
    print(df)
```

```
   configuration/step  log/value/potential_energy  log/value/pressure log/category
0                   0                          10                  -3            A
1                   1                          10                   5          BBB
```

2024-10-18 15:14 UTC, merged