Only sync GSD files when writing out properties rather than per property
glotzerlab/gsd pull request #54
Opened 2019-10-31 21:26 UTC by vyasr

## Description

See glotzerlab/hoomd-blue#499 for more information.

## How Has This Been Tested?

## Change log

```
Update fsync calls for namelist to only call after all names are added to the list.
```

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/gsd/blob/master/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**GSD Contributor Agreement**](https://github.com/glotzerlab/gsd/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/gsd/blob/master/doc/credits.rst).

2019-11-01 17:37 UTC, vyasr commented
Windows doesn't seem to like my changes, but I'm not sure why since the fsync calls already existed and I'm just changing when they are called.

2019-11-04 12:07 UTC, joaander requested changes

2019-11-04 12:07 UTC, joaander commented on gsd/gsd.c
> -    #ifdef _WIN32
Revert this change and the similar ones below to fix the failing test. This was fixed in #51.

2019-11-07 12:29 UTC, joaander commented
/azp run pypi

2019-11-07 12:40 UTC, joaander approved these changes
Thanks!

2019-11-07 12:58 UTC, merged